apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: wordpress-db
  name: wordpress-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: wordpress-db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: wordpress-db
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: wordpress
            - name: MYSQL_PASSWORD
              value: wordpress
            - name: MYSQL_RANDOM_ROOT_PASSWORD
              value: "1"
            - name: MYSQL_USER
              value: wordpress
          image: mysql:8.0
          name: wordpress-db
          ports:
            - containerPort: 3306
              protocol: TCP
            - containerPort: 33060
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: wordpress-db
      hostname: wordpress-db
      restartPolicy: Always
      volumes:
        - name: wordpress-db
          persistentVolumeClaim:
            claimName: wordpress-db
