apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    io.kompose.service: wordpress
  name: wordpress
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /var/storage/wordpress