apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: wordpress-db
  name: wordpress-db
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
